// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webAPI.Infrastructure;

#nullable disable

namespace webAPI.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    partial class ConnectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webAPI.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("webAPI.Domain.Models.ClientDestination", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "DestinationId");

                    b.HasIndex("DestinationId");

                    b.ToTable("ClientDestinations");
                });

            modelBuilder.Entity("webAPI.Domain.Models.ClientTravel", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("TravelId")
                        .HasColumnType("int");

                    b.HasKey("ClientId", "TravelId");

                    b.HasIndex("TravelId");

                    b.ToTable("ClientTravels");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Travel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("DestinationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.ToTable("Travels");
                });

            modelBuilder.Entity("webAPI.Domain.Models.ClientDestination", b =>
                {
                    b.HasOne("webAPI.Domain.Models.Client", "Client")
                        .WithMany("ClientDestinations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webAPI.Domain.Models.Destination", "Destination")
                        .WithMany("ClientDestinations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("webAPI.Domain.Models.ClientTravel", b =>
                {
                    b.HasOne("webAPI.Domain.Models.Client", "Client")
                        .WithMany("ClientTravels")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webAPI.Domain.Models.Travel", "Travel")
                        .WithMany("ClientTravels")
                        .HasForeignKey("TravelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Travel");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Travel", b =>
                {
                    b.HasOne("webAPI.Domain.Models.Destination", "Destination")
                        .WithMany("Travels")
                        .HasForeignKey("DestinationId");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Client", b =>
                {
                    b.Navigation("ClientDestinations");

                    b.Navigation("ClientTravels");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Destination", b =>
                {
                    b.Navigation("ClientDestinations");

                    b.Navigation("Travels");
                });

            modelBuilder.Entity("webAPI.Domain.Models.Travel", b =>
                {
                    b.Navigation("ClientTravels");
                });
#pragma warning restore 612, 618
        }
    }
}
